name: nombre del pipeline
on:
  push:
    branches: ["main"]
    workflow_dispatch:

jobs:
  echo-job:
    name: Run Echo Commands
    runs-on: ubuntu-latest

    steps:
      -name: Step1
      run: echo "Hello! This is a simple Github Actions pipeline."

      -name: Step2
      run: echo "The current date and time is:$(date)"
